shortest_path/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import (index_view, get_shortest_path, calc_path)

app_name = 'index'

urlpatterns = [
    path('', index_view, name='index'),
    path('get_shortest_path', get_shortest_path, name='get_shortest_path'),
    path('download_shortest_path', calc_path, name='download_shortest_path'),
]

shortest_path_application/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shortest_path.urls', namespace="index")),
    # path('appointments/', include('appointments.urls', namespace="appointments")),

]

shortest_path/models.py
from django.db import models

# Create your models here.

shortest_path/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.conf import settings
from django.http import HttpResponse, JsonResponse
import io
import pandas
import networkx as nx


cities = ["Annotto Bay", "Black River",
          "Christiana","Falmouth","KINGSTON","Lucea","Mandeville","May Pen",
          "Montego Bay","Morant Bay","Ocho Rios","Port Antonio","Port Maria",
          "St. Anns Bay","Savanna-La-Mar","Spanish Town"]

# Function based views for views

def index_view(request):
	filename = settings.DOCUMENT_PATH
	df = pandas.read_excel(filename)
	str_io = io.StringIO()
	df.to_html(buf=str_io, classes='table table-striped table-bordered table-hover text-nowrap shortest_path_table', justify='initial', border=0)
	html_str = str_io.getvalue()
	return render(request, 'shortest_path/index.html', {"shortest_path_table" : html_str, "towns": list(df['Towns']) })

@require_http_methods(["POST"])
def get_shortest_path(request):

	# prepare graph of town
	G = prepareGraph();

	source = request.POST['source']
	destination = request.POST['destination']

	source = source.lower()
	destination = destination.lower()

	dijkstra_path = nx.dijkstra_path(G, source, destination)
	dijkstra_path_length = nx.dijkstra_path_length(G, source, destination)

	return JsonResponse({'dijkstra_path': dijkstra_path,'dijkstra_path_length': dijkstra_path_length})

@require_http_methods(["POST"])
def calc_path(request):

	filename = "dijkstra_path_shortest.xlsx"

	G = prepareGraph()
	df = prepareDf()
	
	data = []
	towns = sorted(list(set(df["Town"])))

	for t in df['Town']:
		row = []
		for r in df['Town']:
		    if nx.has_path(G, t.lower(), r.lower()):
		        row.append(nx.dijkstra_path_length(G, t.lower(), r.lower()))
		data.append(row)
	shortDistanceDf = pandas.DataFrame(data, columns=df['Town'], index=towns)

	workbook = io.BytesIO()
	PandasWriter = pandas.ExcelWriter(workbook, engine='xlsxwriter')
	shortDistanceDf.to_excel(PandasWriter, sheet_name='Shortest Distance')
	PandasWriter.save()
	PandasWriter.close()

	workbook.seek(0)

	response = HttpResponse(workbook.read(), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
	response['Content-Disposition'] = f'attachment; filename={filename}'

	return response


def prepareGraph():	

	df = prepareDf()

	# create graph
	G = nx.Graph()

	# add nodes

	G.add_nodes_from(df['Town'].str.lower())

	# create edges

	graph = []
	j=0
	l=0
	for i, t in df.iterrows():
		if(j >= len(cities)):
			j = 0
		for city in cities:
			graph.append((t['Town'].lower(),city.lower(),int(t['d'+str(j)])))
			j+=1

	# add egdes

	G.add_weighted_edges_from( graph )

	return G

def prepareDf():
	# read the cities and distance from 17 towns

	filename = settings.CITIES_AND_TOWN
	df = pandas.read_excel(filename)

	return df

shortest_path/templates/shortest_path/index.html
{% extends "shortest_path/template/home.template.html" %}
{% load staticfiles %}

{% block title %}
{{ block.super }}
{% endblock %}


{% block page_content %}

<!-- Jumbotrom -->

<div id="googlemaps" ng-init="initializeMaps()" class="page-header header-filter ng-cloak hide-on-med-and-down" data-parallax="active"
  style="transform: translate3d(0px, 0px, 0px);background-size: contain;">
 </div>
<div class="main_header_section main-containter" data-parallax="active" style="position:absolute;bottom:0;">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12 d-sm-block">
        </div>
        <div class="col-lg-6 shadow rounded col-md-6 col-sm-12" style="background-color: rgba(255, 255, 255, .66);">
            <div class="promo_content">
                <h1 class="title-xl-bold" style="color: #4e4848;"> Shortest Paths Between Jamaican Towns Project  </h1>
            </div>
        </div>
    </div>
</div>

<!-- Contact Section -->

<div class="contact_us_section section general_padding main-containter">
    <div class="main-containter">
        <div class="row mt-3">
            <div class="col text-center">
                <h1 class="section_header_title">Group Members</h1>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col text-left">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-4">
                        <div class="row contact-card bg-light">
                            <div class="col-lg-3 col-sm-12 pl-0 text-center">
                                <img class="contact_us_icons" src="/static/images/man.png">
                            </div>
                            <div class="col-lg-9 col-sm-12 text-center-sm p-0">
                                <h3 class="mb-2 font-weight-bold">JeVaughn Ferguson</h3>
                                <p class="mb-0 text-muted">1206909</p>
                                <p class="mb-0 text-muted">da3ferg@gmail.com</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-4">
                        <div class="row contact-card bg-light">
                            <div class="col-lg-3 col-sm-12 pl-0 text-center">
                                <img class="contact_us_icons" src="/static/images/woman.png">
                            </div>
                            <div class="col-lg-9 col-sm-12 text-center-sm p-0">
                                <h3 class="mb-2 font-weight-bold">Shanel Bailey</h3>
                                <p class="mb-0 text-muted">1600170</p>
                                <p class="mb-0 text-muted">shanelbailey.sb@gmail</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-4">
                        <div class="row contact-card bg-light">
                            <div class="col-lg-3 col-sm-12 pl-0 text-center">
                                <img class="contact_us_icons" src="/static/images/man.png">
                            </div>
                            <div class="col-lg-9 col-sm-12 text-center-sm p-0">
                                <h3 class="mb-2 font-weight-bold">Leathon Gregory</h3>
                                <p class="mb-0 text-muted">1601444</p>
                                <p class="mb-0 text-muted">leathongregory@gmail.com</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Services Section -->

<div class="services_section section container">
    <div class="main-containter">
        <div class="row mt-5 mb-2">
            <div class="col text-center">
                <h1 class="services_section_header section_header_title">Table Showing The Shortest Distance Between 51 Towns using the <b>Dijkstra Algorithm</b></h1>
            </div>
        </div>
        <div class="row mt-3">
            <div class="table-responsive">
                {{shortest_path_table | safe }}
            </div>
            <caption class="pt-5 pb-5">
                <form action="{% url 'index:download_shortest_path' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-light">Download</button>
                </form>
            </caption>
        </div>
    </div>
</div>

<!-- FAQ Section -->

<div class="faq_section section general_padding main-containter">
    <div class="main-containter">
        <div class="row mt-2 mb-2">
            <div class="col text-center">
                <h1 class="section_header_title ">Distance and Route Between Two Cities</h1>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-lg-12 col-md-12 col-sm-12 text-right">
                <div class="row">
                    <div class="col">
                      <form method="post" id="route_cost" action="{% url 'index:get_shortest_path' %}">
                        {% csrf_token %}
                                <table class="table">
                                    <tr>
                                        <td style="width:75%;">
                                            <table style="width: 100%;" class="table table-borderless">
                                                <tr>
                                                    <td>
                                                       <label for="distanceFrom">Distance From</label> 
                                                    </td>
                                                    <td>
                                                        <select class="form-control" style="height: 32px" name="source" id="distanceFrom">
                                                          {% for i in towns %}
                                                          <option value="{{i}}">{{i | title}}</option>
                                                          {% endfor %}
                                                        </select>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <label for="distanceTo">Distance To</label>
                                                    </td>
                                                    <td>
                                                        <select name="destination" style="height: 32px" class="form-control" id="distanceTo">
                                                          {% for i in towns %}
                                                          <option value="{{i}}">{{i | title}}</option>
                                                          {% endfor %}
                                                        </select>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td style="text-align: left;vertical-align: middle;" rowspan="3">
                                                <button style="font-size: 18px;" type="submit" class="btn btn-primary">Get Route and Distance</button>
                                        </td>
                                    </tr>
                                </table>
                        </form>

                        <table class="table">
                            <tr>
                                <td style="text-align: left" colspan="2">
                                    <div id="results"></div>
                                    <div id="results_cost"></div>
                                    <img id="sub_graph" class="img-responsive">
                                </td>
                            </tr>
                        </table>
                    </div>
                </div> 
            </div>
        </div>
    </div>
</div>



<!-- Main Footer Section -->


{% endblock page_content %}

{% block additional_scripts %}
{% endblock %}

shortest_path/templates/shortest_path/template/home.template.html
{% extends "shortest_path/template/index.template.html" %}
{% load staticfiles %}

{% block additional_styles %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
{% endblock %}

<!-- Navbard -->
{% block navbar_content %}
<div class="fixed-nav border-bottom-light">
    <nav class="navbar navbar-expand-lg navbar-light px-0 pt-3 container">
        <a class="navbar-brand mr-5" href="{% url 'index:index' %}">
            <span class="mb-0 h1 mobile-text-sm"> Analysis of Algorithm </span>
        </a>
    </nav>
</div>
{% endblock navbar_content%}

<!--  Page Content -->
{% block content %}
<div id="home-content-container">
    {% block page_content %}
    {% endblock page_content %}
</div>
{% endblock content%}



{% block footer_content %}

<div class="footer">
    <div class="container">
        <ul>
            <li>
                <p>&copy; 2018 Copyright. All Rights Reserved.</p>
            </li>
        </ul>
    </div>
</div>
{% endblock footer_content%}

shortest_path/templates/shortest_path/template/index.template.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %} Analysis of Algorithm {% endblock title %}</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/site_index.css' %}" type="text/css">
    
        {% block additional_styles %}{% endblock %}
    </head>
    <body>

        {% block navbar_content %}
        {% endblock navbar_content%}

        {% block content %}
        {% endblock content%}

        {% block footer_content %}
        {% endblock footer_content%}
        
    <script type="text/javascript" src="{% static 'jquery/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/site_index.js' %}"></script>
    <!-- Include the Google Maps API library - required for embedding maps -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAnsSTapw1OcTHwiYukC9iFxtamxP0f6-E"></script>
    {% block additional_scripts %}{% endblock %}
    </body>
</html>
    
    